=== api-evangelist/amazon-dms/json-schema/amazon-dms-event-subscription-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-dms/refs/heads/main/json-schema/amazon-dms-event-subscription-schema.json",
  "title": "EventSubscription",
  "description": "Describes an event notification subscription created by the <code>CreateEventSubscription</code> operation.",
  "type": "object",
  "properties": {
    "CustomerAwsId": {
      "allOf": [
        {
          "$ref": "#/components/schemas/String"
        },
        {
          "description": "The Amazon Web Services customer account associated with the DMS event notification subscription."
        }
      ]
    },
    "CustSubscriptionId": {
      "allOf": [
        {
          "$ref": "#/components/schemas/String"
        },
        {
          "description": "The DMS event notification subscription Id."
        }
      ]
    },
    "SnsTopicArn": {
      "allOf": [
        {
          "$ref": "#/components/schemas/String"
        },
        {
          "description": "The topic ARN of the DMS event notification subscription."
        }
      ]
    },
    "Status": {
      "allOf": [
        {
          "$ref": "#/components/schemas/String"
        },
        {
          "description": "<p>The status of the DMS event notification subscription.</p> <p>Constraints:</p> <p>Can be one of the following: creating | modifying | deleting | active | no-permission | topic-not-exist</p> <p>The status \"no-permission\" indicates that DMS no longer has permission to post to the SNS topic. The status \"topic-not-exist\" indicates that the topic was deleted after the subscription was created.</p>"
        }
      ]
    },
    "SubscriptionCreationTime": {
      "allOf": [
        {
          "$ref": "#/components/schemas/String"
        },
        {
          "description": "The time the DMS event notification subscription was created."
        }
      ]
    },
    "SourceType": {
      "allOf": [
        {
          "$ref": "#/components/schemas/String"
        },
        {
          "description": "<p> The type of DMS resource that generates events. </p> <p>Valid values: replication-instance | replication-server | security-group | replication-task</p>"
        }
      ]
    },
    "SourceIdsList": {
      "allOf": [
        {
          "$ref": "#/components/schemas/SourceIdsList"
        },
        {
          "description": "A list of source Ids for the event subscription."
        }
      ]
    },
    "EventCategoriesList": {
      "allOf": [
        {
          "$ref": "#/components/schemas/EventCategoriesList"
        },
        {
          "description": "A lists of event categories."
        }
      ]
    },
    "Enabled": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Boolean"
        },
        {
          "description": "Boolean value that indicates if the event subscription is enabled."
        }
      ]
    }
  }
}

=== api-evangelist/amazon-dms/examples/amazon-dms-event-subscription-example.json
{
  "CustomerAwsId": "example-8199",
  "CustSubscriptionId": "example-4306",
  "SnsTopicArn": "example-1505",
  "Status": "example-8201",
  "SubscriptionCreationTime": "example-8396",
  "SourceType": "example-6574",
  "SourceIdsList": "example-7393",
  "EventCategoriesList": "example-1891",
  "Enabled": "example-1756"
}
