=== api-evangelist/amazon-dms/json-schema/amazon-dms-table-statistics-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-dms/refs/heads/main/json-schema/amazon-dms-table-statistics-schema.json",
  "title": "TableStatistics",
  "description": "Provides a collection of table statistics in response to a request by the <code>DescribeTableStatistics</code> operation.",
  "type": "object",
  "properties": {
    "SchemaName": {
      "allOf": [
        {
          "$ref": "#/components/schemas/String"
        },
        {
          "description": "The schema name."
        }
      ]
    },
    "TableName": {
      "allOf": [
        {
          "$ref": "#/components/schemas/String"
        },
        {
          "description": "The name of the table."
        }
      ]
    },
    "Inserts": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Long"
        },
        {
          "description": "The number of insert actions performed on a table."
        }
      ]
    },
    "Deletes": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Long"
        },
        {
          "description": "The number of delete actions performed on a table."
        }
      ]
    },
    "Updates": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Long"
        },
        {
          "description": "The number of update actions performed on a table."
        }
      ]
    },
    "Ddls": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Long"
        },
        {
          "description": "The data definition language (DDL) used to build and modify the structure of your tables."
        }
      ]
    },
    "AppliedInserts": {
      "allOf": [
        {
          "$ref": "#/components/schemas/LongOptional"
        },
        {
          "description": "The number of insert actions applied on a target table."
        }
      ]
    },
    "AppliedDeletes": {
      "allOf": [
        {
          "$ref": "#/components/schemas/LongOptional"
        },
        {
          "description": "The number of delete actions applied on a target table."
        }
      ]
    },
    "AppliedUpdates": {
      "allOf": [
        {
          "$ref": "#/components/schemas/LongOptional"
        },
        {
          "description": "The number of update actions applied on a target table."
        }
      ]
    },
    "AppliedDdls": {
      "allOf": [
        {
          "$ref": "#/components/schemas/LongOptional"
        },
        {
          "description": "The number of data definition language (DDL) statements used to build and modify the structure of your tables applied on the target."
        }
      ]
    },
    "FullLoadRows": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Long"
        },
        {
          "description": "The number of rows added during the full load operation."
        }
      ]
    },
    "FullLoadCondtnlChkFailedRows": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Long"
        },
        {
          "description": "The number of rows that failed conditional checks during the full load operation (valid only for migrations where DynamoDB is the target)."
        }
      ]
    },
    "FullLoadErrorRows": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Long"
        },
        {
          "description": "The number of rows that failed to load during the full load operation (valid only for migrations where DynamoDB is the target)."
        }
      ]
    },
    "FullLoadStartTime": {
      "allOf": [
        {
          "$ref": "#/components/schemas/TStamp"
        },
        {
          "description": "The time when the full load operation started."
        }
      ]
    },
    "FullLoadEndTime": {
      "allOf": [
        {
          "$ref": "#/components/schemas/TStamp"
        },
        {
          "description": "The time when the full load operation completed."
        }
      ]
    },
    "FullLoadReloaded": {
      "allOf": [
        {
          "$ref": "#/components/schemas/BooleanOptional"
        },
        {
          "description": "A value that indicates if the table was reloaded (<code>true</code>) or loaded as part of a new full load operation (<code>false</code>)."
        }
      ]
    },
    "LastUpdateTime": {
      "allOf": [
        {
          "$ref": "#/components/schemas/TStamp"
        },
        {
          "description": "The last time a table was updated."
        }
      ]
    },
    "TableState": {
      "allOf": [
        {
          "$ref": "#/components/schemas/String"
        },
        {
          "description": "<p>The state of the tables described.</p> <p>Valid states: Table does not exist | Before load | Full load | Table completed | Table cancelled | Table error | Table is being reloaded</p>"
        }
      ]
    },
    "ValidationPendingRecords": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Long"
        },
        {
          "description": "The number of records that have yet to be validated."
        }
      ]
    },
    "ValidationFailedRecords": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Long"
        },
        {
          "description": "The number of records that failed validation."
        }
      ]
    },
    "ValidationSuspendedRecords": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Long"
        },
        {
          "description": "The number of records that couldn't be validated."
        }
      ]
    },
    "ValidationState": {
      "allOf": [
        {
          "$ref": "#/components/schemas/String"
        },
        {
          "description": "<p>The validation state of the table.</p> <p>This parameter can have the following values:</p> <ul> <li> <p>Not enabled \u2013 Validation isn't enabled for the table in the migration task.</p> </li> <li> <p>Pending records \u2013 Some records in the table are waiting for validation.</p> </li> <li> <p>Mismatched records \u2013 Some records in the table don't match between the source and target.</p> </li> <li> <p>Suspended records \u2013 Some records in the table couldn't be validated.</p> </li> <li> <p>No primary key \u2013The table couldn't be validated because it has no primary key.</p> </li> <li> <p>Table error \u2013 The table wasn't validated because it's in an error state and some data wasn't migrated.</p> </li> <li> <p>Validated \u2013 All rows in the table are validated. If the table is updated, the status can change from Validated.</p> </li> <li> <p>Error \u2013 The table couldn't be validated because of an unexpected error.</p> </li> <li> <p>Pending validation \u2013 The table is waiting validation.</p> </li> <li> <p>Preparing table \u2013 Preparing the table enabled in the migration task for validation.</p> </li> <li> <p>Pending revalidation \u2013 All rows in the table are pending validation after the table was updated.</p> </li> </ul>"
        }
      ]
    },
    "ValidationStateDetails": {
      "allOf": [
        {
          "$ref": "#/components/schemas/String"
        },
        {
          "description": "Additional details about the state of validation."
        }
      ]
    }
  }
}

=== api-evangelist/amazon-dms/examples/amazon-dms-table-statistics-example.json
{
  "SchemaName": "example-4030",
  "TableName": "example-9612",
  "Inserts": "example-1168",
  "Deletes": "example-3022",
  "Updates": "example-7184",
  "Ddls": "example-9785",
  "AppliedInserts": "example-2694",
  "AppliedDeletes": "example-1619",
  "AppliedUpdates": "example-2427",
  "AppliedDdls": "example-4999",
  "FullLoadRows": "example-9859",
  "FullLoadCondtnlChkFailedRows": "example-1134",
  "FullLoadErrorRows": "example-4117",
  "FullLoadStartTime": "example-6540",
  "FullLoadEndTime": "example-4496",
  "FullLoadReloaded": "example-4642",
  "LastUpdateTime": "example-4329",
  "TableState": "example-3924",
  "ValidationPendingRecords": "example-2475",
  "ValidationFailedRecords": "example-7817",
  "ValidationSuspendedRecords": "example-9037",
  "ValidationState": "example-2550",
  "ValidationStateDetails": "example-7478"
}
