=== api-evangelist/amazon-dms/json-schema/amazon-dms-replication-task-assessment-run-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-dms/refs/heads/main/json-schema/amazon-dms-replication-task-assessment-run-schema.json",
  "title": "ReplicationTaskAssessmentRun",
  "description": "<p>Provides information that describes a premigration assessment run that you have started using the <code>StartReplicationTaskAssessmentRun</code> operation.</p> <p>Some of the information appears based on other operations that can return the <code>ReplicationTaskAssessmentRun</code> object.</p>",
  "type": "object",
  "properties": {
    "ReplicationTaskAssessmentRunArn": {
      "allOf": [
        {
          "$ref": "#/components/schemas/String"
        },
        {
          "description": "Amazon Resource Name (ARN) of this assessment run."
        }
      ]
    },
    "ReplicationTaskArn": {
      "allOf": [
        {
          "$ref": "#/components/schemas/String"
        },
        {
          "description": "ARN of the migration task associated with this premigration assessment run."
        }
      ]
    },
    "Status": {
      "allOf": [
        {
          "$ref": "#/components/schemas/String"
        },
        {
          "description": "<p>Assessment run status. </p> <p>This status can have one of the following values:</p> <ul> <li> <p> <code>\"cancelling\"</code> \u2013 The assessment run was canceled by the <code>CancelReplicationTaskAssessmentRun</code> operation.</p> </li> <li> <p> <code>\"deleting\"</code> \u2013 The assessment run was deleted by the <code>DeleteReplicationTaskAssessmentRun</code> operation.</p> </li> <li> <p> <code>\"failed\"</code> \u2013 At least one individual assessment completed with a <code>failed</code> status.</p> </li> <li> <p> <code>\"error-provisioning\"</code> \u2013 An internal error occurred while resources were provisioned (during <code>provisioning</code> status).</p> </li> <li> <p> <code>\"error-executing\"</code> \u2013 An internal error occurred while individual assessments ran (during <code>running</code> status).</p> </li> <li> <p> <code>\"invalid state\"</code> \u2013 The assessment run is in an unknown state.</p> </li> <li> <p> <code>\"passed\"</code> \u2013 All individual assessments have completed, and none has a <code>failed</code> status.</p> </li> <li> <p> <code>\"provisioning\"</code> \u2013 Resources required to run individual assessments are being provisioned.</p> </li> <li> <p> <code>\"running\"</code> \u2013 Individual assessments are being run.</p> </li> <li> <p> <code>\"starting\"</code> \u2013 The assessment run is starting, but resources are not yet being provisioned for individual assessments.</p> </li> </ul>"
        }
      ]
    },
    "ReplicationTaskAssessmentRunCreationDate": {
      "allOf": [
        {
          "$ref": "#/components/schemas/TStamp"
        },
        {
          "description": "Date on which the assessment run was created using the <code>StartReplicationTaskAssessmentRun</code> operation."
        }
      ]
    },
    "AssessmentProgress": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ReplicationTaskAssessmentRunProgress"
        },
        {
          "description": "Indication of the completion progress for the individual assessments specified to run."
        }
      ]
    },
    "LastFailureMessage": {
      "allOf": [
        {
          "$ref": "#/components/schemas/String"
        },
        {
          "description": "Last message generated by an individual assessment failure."
        }
      ]
    },
    "ServiceAccessRoleArn": {
      "allOf": [
        {
          "$ref": "#/components/schemas/String"
        },
        {
          "description": "ARN of the service role used to start the assessment run using the <code>StartReplicationTaskAssessmentRun</code> operation. The role must allow the <code>iam:PassRole</code> action."
        }
      ]
    },
    "ResultLocationBucket": {
      "allOf": [
        {
          "$ref": "#/components/schemas/String"
        },
        {
          "description": "Amazon S3 bucket where DMS stores the results of this assessment run."
        }
      ]
    },
    "ResultLocationFolder": {
      "allOf": [
        {
          "$ref": "#/components/schemas/String"
        },
        {
          "description": "Folder in an Amazon S3 bucket where DMS stores the results of this assessment run."
        }
      ]
    },
    "ResultEncryptionMode": {
      "allOf": [
        {
          "$ref": "#/components/schemas/String"
        },
        {
          "description": "Encryption mode used to encrypt the assessment run results."
        }
      ]
    },
    "ResultKmsKeyArn": {
      "allOf": [
        {
          "$ref": "#/components/schemas/String"
        },
        {
          "description": "ARN of the KMS encryption key used to encrypt the assessment run results."
        }
      ]
    },
    "AssessmentRunName": {
      "allOf": [
        {
          "$ref": "#/components/schemas/String"
        },
        {
          "description": "Unique name of the assessment run."
        }
      ]
    }
  }
}

=== api-evangelist/amazon-dms/examples/amazon-dms-replication-task-assessment-run-example.json
{
  "ReplicationTaskAssessmentRunArn": "example-4671",
  "ReplicationTaskArn": "example-8213",
  "Status": "example-9763",
  "ReplicationTaskAssessmentRunCreationDate": "example-6413",
  "AssessmentProgress": "example-3781",
  "LastFailureMessage": "example-7734",
  "ServiceAccessRoleArn": "example-6169",
  "ResultLocationBucket": "example-2890",
  "ResultLocationFolder": "example-4326",
  "ResultEncryptionMode": "example-9965",
  "ResultKmsKeyArn": "example-7505",
  "AssessmentRunName": "example-9022"
}
