=== api-evangelist/amazon-dms/json-schema/amazon-dms-certificate-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-dms/refs/heads/main/json-schema/amazon-dms-certificate-schema.json",
  "title": "Certificate",
  "description": "The SSL certificate that can be used to encrypt connections between the endpoints and the replication instance.",
  "type": "object",
  "properties": {
    "CertificateIdentifier": {
      "allOf": [
        {
          "$ref": "#/components/schemas/String"
        },
        {
          "description": "A customer-assigned name for the certificate. Identifiers must begin with a letter and must contain only ASCII letters, digits, and hyphens. They can't end with a hyphen or contain two consecutive hyphens."
        }
      ]
    },
    "CertificateCreationDate": {
      "allOf": [
        {
          "$ref": "#/components/schemas/TStamp"
        },
        {
          "description": "The date that the certificate was created."
        }
      ]
    },
    "CertificatePem": {
      "allOf": [
        {
          "$ref": "#/components/schemas/String"
        },
        {
          "description": "The contents of a <code>.pem</code> file, which contains an X.509 certificate."
        }
      ]
    },
    "CertificateWallet": {
      "allOf": [
        {
          "$ref": "#/components/schemas/CertificateWallet"
        },
        {
          "description": "The location of an imported Oracle Wallet certificate for use with SSL. Example: <code>filebase64(\"${path.root}/rds-ca-2019-root.sso\")</code> "
        }
      ]
    },
    "CertificateArn": {
      "allOf": [
        {
          "$ref": "#/components/schemas/String"
        },
        {
          "description": "The Amazon Resource Name (ARN) for the certificate."
        }
      ]
    },
    "CertificateOwner": {
      "allOf": [
        {
          "$ref": "#/components/schemas/String"
        },
        {
          "description": "The owner of the certificate."
        }
      ]
    },
    "ValidFromDate": {
      "allOf": [
        {
          "$ref": "#/components/schemas/TStamp"
        },
        {
          "description": "The beginning date that the certificate is valid."
        }
      ]
    },
    "ValidToDate": {
      "allOf": [
        {
          "$ref": "#/components/schemas/TStamp"
        },
        {
          "description": "The final date that the certificate is valid."
        }
      ]
    },
    "SigningAlgorithm": {
      "allOf": [
        {
          "$ref": "#/components/schemas/String"
        },
        {
          "description": "The signing algorithm for the certificate."
        }
      ]
    },
    "KeyLength": {
      "allOf": [
        {
          "$ref": "#/components/schemas/IntegerOptional"
        },
        {
          "description": "The key length of the cryptographic algorithm being used."
        }
      ]
    }
  }
}

=== api-evangelist/amazon-dms/examples/amazon-dms-certificate-example.json
{
  "CertificateIdentifier": "example-6111",
  "CertificateCreationDate": "example-8018",
  "CertificatePem": "example-8159",
  "CertificateWallet": "example-9783",
  "CertificateArn": "example-5975",
  "CertificateOwner": "example-6689",
  "ValidFromDate": "example-6177",
  "ValidToDate": "example-3868",
  "SigningAlgorithm": "example-6820",
  "KeyLength": "example-2089"
}
