=== api-evangelist/amazon-dms/json-schema/amazon-dms-replication-task-stats-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-dms/refs/heads/main/json-schema/amazon-dms-replication-task-stats-schema.json",
  "title": "ReplicationTaskStats",
  "description": "In response to a request by the <code>DescribeReplicationTasks</code> operation, this object provides a collection of statistics about a replication task.",
  "type": "object",
  "properties": {
    "FullLoadProgressPercent": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Integer"
        },
        {
          "description": "The percent complete for the full load migration task."
        }
      ]
    },
    "ElapsedTimeMillis": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Long"
        },
        {
          "description": "The elapsed time of the task, in milliseconds."
        }
      ]
    },
    "TablesLoaded": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Integer"
        },
        {
          "description": "The number of tables loaded for this task."
        }
      ]
    },
    "TablesLoading": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Integer"
        },
        {
          "description": "The number of tables currently loading for this task."
        }
      ]
    },
    "TablesQueued": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Integer"
        },
        {
          "description": "The number of tables queued for this task."
        }
      ]
    },
    "TablesErrored": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Integer"
        },
        {
          "description": "The number of errors that have occurred during this task."
        }
      ]
    },
    "FreshStartDate": {
      "allOf": [
        {
          "$ref": "#/components/schemas/TStamp"
        },
        {
          "description": "The date the replication task was started either with a fresh start or a target reload."
        }
      ]
    },
    "StartDate": {
      "allOf": [
        {
          "$ref": "#/components/schemas/TStamp"
        },
        {
          "description": "The date the replication task was started either with a fresh start or a resume. For more information, see <a href=\"https://docs.aws.amazon.com/dms/latest/APIReference/API_StartReplicationTask.html#DMS-StartReplicationTask-request-StartReplicationTaskType\">StartReplicationTaskType</a>."
        }
      ]
    },
    "StopDate": {
      "allOf": [
        {
          "$ref": "#/components/schemas/TStamp"
        },
        {
          "description": "The date the replication task was stopped."
        }
      ]
    },
    "FullLoadStartDate": {
      "allOf": [
        {
          "$ref": "#/components/schemas/TStamp"
        },
        {
          "description": "The date the replication task full load was started."
        }
      ]
    },
    "FullLoadFinishDate": {
      "allOf": [
        {
          "$ref": "#/components/schemas/TStamp"
        },
        {
          "description": "The date the replication task full load was completed."
        }
      ]
    }
  }
}

=== api-evangelist/amazon-dms/examples/amazon-dms-replication-task-stats-example.json
{
  "FullLoadProgressPercent": "example-5122",
  "ElapsedTimeMillis": "example-2904",
  "TablesLoaded": "example-7248",
  "TablesLoading": "example-6548",
  "TablesQueued": "example-7804",
  "TablesErrored": "example-7115",
  "FreshStartDate": "example-3611",
  "StartDate": "example-9892",
  "StopDate": "example-6002",
  "FullLoadStartDate": "example-3620",
  "FullLoadFinishDate": "example-8138"
}
