=== api-evangelist/amazon-dms/json-schema/amazon-dms-replication-instance-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-dms/refs/heads/main/json-schema/amazon-dms-replication-instance-schema.json",
  "title": "ReplicationInstance",
  "description": "Provides information that defines a replication instance.",
  "type": "object",
  "properties": {
    "ReplicationInstanceIdentifier": {
      "allOf": [
        {
          "$ref": "#/components/schemas/String"
        },
        {
          "description": "<p>The replication instance identifier is a required parameter. This parameter is stored as a lowercase string.</p> <p>Constraints:</p> <ul> <li> <p>Must contain 1-63 alphanumeric characters or hyphens.</p> </li> <li> <p>First character must be a letter.</p> </li> <li> <p>Cannot end with a hyphen or contain two consecutive hyphens.</p> </li> </ul> <p>Example: <code>myrepinstance</code> </p>"
        }
      ]
    },
    "ReplicationInstanceClass": {
      "allOf": [
        {
          "$ref": "#/components/schemas/String"
        },
        {
          "description": "<p>The compute and memory capacity of the replication instance as defined for the specified replication instance class. It is a required parameter, although a default value is pre-selected in the DMS console.</p> <p>For more information on the settings and capacities for the available replication instance classes, see <a href=\"https://docs.aws.amazon.com/dms/latest/userguide/CHAP_ReplicationInstance.html#CHAP_ReplicationInstance.InDepth\"> Selecting the right DMS replication instance for your migration</a>. </p>"
        }
      ]
    },
    "ReplicationInstanceStatus": {
      "allOf": [
        {
          "$ref": "#/components/schemas/String"
        },
        {
          "description": "<p>The status of the replication instance. The possible return values include:</p> <ul> <li> <p> <code>\"available\"</code> </p> </li> <li> <p> <code>\"creating\"</code> </p> </li> <li> <p> <code>\"deleted\"</code> </p> </li> <li> <p> <code>\"deleting\"</code> </p> </li> <li> <p> <code>\"failed\"</code> </p> </li> <li> <p> <code>\"modifying\"</code> </p> </li> <li> <p> <code>\"upgrading\"</code> </p> </li> <li> <p> <code>\"rebooting\"</code> </p> </li> <li> <p> <code>\"resetting-master-credentials\"</code> </p> </li> <li> <p> <code>\"storage-full\"</code> </p> </li> <li> <p> <code>\"incompatible-credentials\"</code> </p> </li> <li> <p> <code>\"incompatible-network\"</code> </p> </li> <li> <p> <code>\"maintenance\"</code> </p> </li> </ul>"
        }
      ]
    },
    "AllocatedStorage": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Integer"
        },
        {
          "description": "The amount of storage (in gigabytes) that is allocated for the replication instance."
        }
      ]
    },
    "InstanceCreateTime": {
      "allOf": [
        {
          "$ref": "#/components/schemas/TStamp"
        },
        {
          "description": "The time the replication instance was created."
        }
      ]
    },
    "VpcSecurityGroups": {
      "allOf": [
        {
          "$ref": "#/components/schemas/VpcSecurityGroupMembershipList"
        },
        {
          "description": "The VPC security group for the instance."
        }
      ]
    },
    "AvailabilityZone": {
      "allOf": [
        {
          "$ref": "#/components/schemas/String"
        },
        {
          "description": "The Availability Zone for the instance."
        }
      ]
    },
    "ReplicationSubnetGroup": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ReplicationSubnetGroup"
        },
        {
          "description": "The subnet group for the replication instance."
        }
      ]
    },
    "PreferredMaintenanceWindow": {
      "allOf": [
        {
          "$ref": "#/components/schemas/String"
        },
        {
          "description": "The maintenance window times for the replication instance. Any pending upgrades to the replication instance are performed during this time."
        }
      ]
    },
    "PendingModifiedValues": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ReplicationPendingModifiedValues"
        },
        {
          "description": "The pending modification values."
        }
      ]
    },
    "MultiAZ": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Boolean"
        },
        {
          "description": " Specifies whether the replication instance is a Multi-AZ deployment. You can't set the <code>AvailabilityZone</code> parameter if the Multi-AZ parameter is set to <code>true</code>. "
        }
      ]
    },
    "EngineVersion": {
      "allOf": [
        {
          "$ref": "#/components/schemas/String"
        },
        {
          "description": "<p>The engine version number of the replication instance.</p> <p>If an engine version number is not specified when a replication instance is created, the default is the latest engine version available.</p> <p>When modifying a major engine version of an instance, also set <code>AllowMajorVersionUpgrade</code> to <code>true</code>.</p>"
        }
      ]
    },
    "AutoMinorVersionUpgrade": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Boolean"
        },
        {
          "description": "Boolean value indicating if minor version upgrades will be automatically applied to the instance."
        }
      ]
    },
    "KmsKeyId": {
      "allOf": [
        {
          "$ref": "#/components/schemas/String"
        },
        {
          "description": "<p>An KMS key identifier that is used to encrypt the data on the replication instance.</p> <p>If you don't specify a value for the <code>KmsKeyId</code> parameter, then DMS uses your default encryption key.</p> <p>KMS creates the default encryption key for your Amazon Web Services account. Your Amazon Web Services account has a different default encryption key for each Amazon Web Services Region.</p>"
        }
      ]
    },
    "ReplicationInstanceArn": {
      "allOf": [
        {
          "$ref": "#/components/schemas/String"
        },
        {
          "description": "The Amazon Resource Name (ARN) of the replication instance."
        }
      ]
    },
    "ReplicationInstancePublicIpAddress": {
      "allOf": [
        {
          "$ref": "#/components/schemas/String"
        },
        {
          "deprecated": true,
          "description": "The public IP address of the replication instance."
        }
      ]
    },
    "ReplicationInstancePrivateIpAddress": {
      "allOf": [
        {
          "$ref": "#/components/schemas/String"
        },
        {
          "deprecated": true,
          "description": "The private IP address of the replication instance."
        }
      ]
    },
    "ReplicationInstancePublicIpAddresses": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ReplicationInstancePublicIpAddressList"
        },
        {
          "description": "One or more public IP addresses for the replication instance."
        }
      ]
    },
    "ReplicationInstancePrivateIpAddresses": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ReplicationInstancePrivateIpAddressList"
        },
        {
          "description": "One or more private IP addresses for the replication instance."
        }
      ]
    },
    "ReplicationInstanceIpv6Addresses": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ReplicationInstanceIpv6AddressList"
        },
        {
          "description": "One or more IPv6 addresses for the replication instance."
        }
      ]
    },
    "PubliclyAccessible": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Boolean"
        },
        {
          "description": " Specifies the accessibility options for the replication instance. A value of <code>true</code> represents an instance with a public IP address. A value of <code>false</code> represents an instance with a private IP address. The default value is <code>true</code>. "
        }
      ]
    },
    "SecondaryAvailabilityZone": {
      "allOf": [
        {
          "$ref": "#/components/schemas/String"
        },
        {
          "description": "The Availability Zone of the standby replication instance in a Multi-AZ deployment."
        }
      ]
    },
    "FreeUntil": {
      "allOf": [
        {
          "$ref": "#/components/schemas/TStamp"
        },
        {
          "description": " The expiration date of the free replication instance that is part of the Free DMS program. "
        }
      ]
    },
    "DnsNameServers": {
      "allOf": [
        {
          "$ref": "#/components/schemas/String"
        },
        {
          "description": "The DNS name servers supported for the replication instance to access your on-premise source or target database."
        }
      ]
    },
    "NetworkType": {
      "allOf": [
        {
          "$ref": "#/components/schemas/String"
        },
        {
          "description": "The type of IP address protocol used by a replication instance, such as IPv4 only or Dual-stack that supports both IPv4 and IPv6 addressing. IPv6 only is not yet supported."
        }
      ]
    }
  }
}

=== api-evangelist/amazon-dms/examples/amazon-dms-replication-instance-example.json
{
  "ReplicationInstanceIdentifier": "example-6832",
  "ReplicationInstanceClass": "example-3735",
  "ReplicationInstanceStatus": "example-1158",
  "AllocatedStorage": "example-5735",
  "InstanceCreateTime": "example-4153",
  "VpcSecurityGroups": "example-9211",
  "AvailabilityZone": "example-7774",
  "ReplicationSubnetGroup": "example-9037",
  "PreferredMaintenanceWindow": "example-5161",
  "PendingModifiedValues": "example-9976",
  "MultiAZ": "example-2566",
  "EngineVersion": "example-8479",
  "AutoMinorVersionUpgrade": "example-8096",
  "KmsKeyId": "example-3256",
  "ReplicationInstanceArn": "example-2166",
  "ReplicationInstancePublicIpAddress": "example-6771",
  "ReplicationInstancePrivateIpAddress": "example-5710",
  "ReplicationInstancePublicIpAddresses": "example-4482",
  "ReplicationInstancePrivateIpAddresses": "example-1414",
  "ReplicationInstanceIpv6Addresses": "example-6852",
  "PubliclyAccessible": "example-2580",
  "SecondaryAvailabilityZone": "example-3601",
  "FreeUntil": "example-4991",
  "DnsNameServers": "example-4837",
  "NetworkType": "example-2658"
}
